OLED_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = yes
SWAP_HANDS_ENABLE = yes

CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes

I2C_DRIVER_REQUIRED = yes
CONVERT_TO = rp2040_ce
SPLIT_KEYBOARD = yes